name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ./vite-app/pnpm-lock.yaml
      - name: Install Dependencies
        working-directory: ./vite-app
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./vite-app
        run: pnpm build
